import "server-only";
import { createHash } from "crypto";

/**
 * CPX Research signs each postback as md5(`${trans_id}-${secretKey}`). This
 * verifies that signature so we only credit surveys CPX Research actually
 * confirmed — never trust a postback's own "status=1" without this check.
 */
export function verifyCpxPostback(transId: string, hash: string): boolean {
  const secret = process.env.CPX_RESEARCH_SECRET_KEY;
  if (!secret) throw new Error("CPX_RESEARCH_SECRET_KEY is not set");
  const expected = createHash("md5").update(`${transId}-${secret}`).digest("hex");
  return expected === hash;
}

export function getCpxAppId(): string {
  const appId = process.env.CPX_RESEARCH_APP_ID;
  if (!appId) throw new Error("CPX_RESEARCH_APP_ID is not set");
  return appId;
}

/**
 * Builds the CPX Research offerwall iframe URL for a given user + product.
 * `secure_hash` proves this URL was generated by us (not spoofed by a user
 * editing ext_user_id in the address bar) — CPX's documented formula is
 * md5(`${ext_user_id}-${secretKey}`), the same pattern as the postback hash.
 * Must only be called server-side: it uses the secret key directly.
 */
export function buildCpxOfferwallUrl(userId: string, productId: string): string {
  const secret = process.env.CPX_RESEARCH_SECRET_KEY;
  if (!secret) throw new Error("CPX_RESEARCH_SECRET_KEY is not set");
  const appId = getCpxAppId();
  const secureHash = createHash("md5").update(`${userId}-${secret}`).digest("hex");

  const params = new URLSearchParams({
    app_id: appId,
    ext_user_id: userId,
    secure_hash: secureHash,
    subid_1: productId,
  });
  return `https://offers.cpx-research.com/index.php?${params.toString()}`;
}
